name = "Boys on Cobblemon"
version = "2026.09.24-2001"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3469b06ec00bf6201ffada33f897dfbb962114115e92a2f36aaa821591db4e8"

[versions]
minecraft = "1.21.1"
fabric = "0.19.5"
